ci: add job to upgrade extensions
This upgrades the PostGIS extension and compares dumps before and after
upgrade. Others will be added later.

This commit also changes the permissions for $GPHOME_SOURCE and
$GPHOME_TARGET inside prepare-installation.sh to gpadmin:gpadmin since
this is required when installing various .gppkg extensions such as
postgis.

Co-authored-by: Orhan Kislal <okislal@vmware.com>

diff --git a/ci/generated/pipeline.yml b/ci/generated/pipeline.yml
--- a/ci/generated/pipeline.yml
+++ b/ci/generated/pipeline.yml
@@ -188,6 +188,54 @@ resources:
     json_key: ((concourse-gcs-resources-service-account-key))
     versioned_file: 6X_STABLE/icw_gporca_centos6_dump/dump.sql.xz
 
+# The postgis dump is a static file that was created by taking objects from the
+# postgis regression tests and "not" dropping the databases associated with
+# them to preserve the objects.
+- name: postgis215_dump
+  type: gcs
+  source:
+    json_key: ((cm-gcs-service-account-key))
+    bucket: ((cm-intermediates-bucket))
+    versioned_file: extensions/postgis215_dump.sql
+
+
+- name: postgis215_gppkg_gpdb6_centos6
+  type: s3
+  source:
+    access_key_id: ((madlib-s3-access_key_id))
+    bucket: ((postgis-gppkg-bucket))
+    region_name: us-west-2
+    secret_access_key: ((madlib-s3-secret_access_key))
+    versioned_file: postgis-2.1.5+pivotal.3-gp6-rhel6-x86_64.gppkg
+
+- name: postgis215_gppkg_gpdb6_centos7
+  type: s3
+  source:
+    access_key_id: ((madlib-s3-access_key_id))
+    bucket: ((postgis-gppkg-bucket))
+    region_name: us-west-2
+    secret_access_key: ((madlib-s3-secret_access_key))
+    versioned_file: postgis-2.1.5+pivotal.3-gp6-rhel7-x86_64.gppkg
+
+- name: postgis215_gppkg_gpdb5_centos6
+  type: s3
+  source:
+    access_key_id: ((madlib-s3-access_key_id))
+    bucket: ((postgis-gppkg-bucket))
+    region_name: us-west-2
+    secret_access_key: ((madlib-s3-secret_access_key))
+    versioned_file: postgis-2.1.5+pivotal.3-gp5-rhel6-x86_64.gppkg
+
+- name: postgis215_gppkg_gpdb5_centos7
+  type: s3
+  source:
+    access_key_id: ((madlib-s3-access_key_id))
+    bucket: ((postgis-gppkg-bucket))
+    region_name: us-west-2
+    secret_access_key: ((madlib-s3-secret_access_key))
+    versioned_file: postgis-2.1.5+pivotal.3-gp5-rhel7-x86_64.gppkg
+
+
 anchors:
   - &ccp_default_params
     action: create
@@ -271,10 +319,12 @@ groups:
       - 5-to-6-primaries-only-centos-6
       - 5-to-6-no-standby-centos-6
       - 5-to-6-retail-demo-centos-6
+      - 5-to-6-extensions-centos-6
       - 5-to-6-link-mode-centos-7
       - 5-to-6-primaries-only-centos-7
       - 5-to-6-no-standby-centos-7
       - 5-to-6-retail-demo-centos-7
+      - 5-to-6-extensions-centos-7
       - publish-release-candidate
   - name: gpupgrade
     jobs:
@@ -298,9 +348,16 @@ groups:
       - 5-to-6-link-mode-centos-6
       - 5-to-6-primaries-only-centos-6
       - 5-to-6-no-standby-centos-6
+      - 5-to-6-extensions-centos-6
       - 5-to-6-link-mode-centos-7
       - 5-to-6-primaries-only-centos-7
       - 5-to-6-no-standby-centos-7
+      - 5-to-6-extensions-centos-7
+  - name: extensions
+    jobs:
+      - build
+      - 5-to-6-extensions-centos-6
+      - 5-to-6-extensions-centos-7
   - name: functional
     jobs:
       - build
@@ -1856,6 +1913,143 @@ jobs:
   on_failure:
     <<: *slack_alert
 
+- name: 5-to-6-extensions-centos-6
+  serial_groups: [5-to-6-extensions]
+  # Specifying serial groups so that only one platform runs at a time. For
+  # example, 5-to-6-centos7 will only run after 5-to-6-centos6 completes. This
+  # will prevent concourse from becoming overloaded.
+  plan:
+    - in_parallel:
+        - get: rpm_enterprise
+          trigger: true
+          passed: [ build ]
+        - get: gpupgrade_src
+          passed: [ build ]
+        - get: rpm_gpdb_source
+          resource: rpm_gpdb5_centos6
+          trigger: true
+        - get: rpm_gpdb_target
+          resource: rpm_gpdb6_centos6
+          trigger: true
+        - get: ccp_src
+        - get: terraform.d
+          params:
+            unpack: true
+        # FIXME: this is not guaranteed to be the same dump generated by the
+        # above binary...
+        - get: sqldump
+          resource: postgis215_dump
+        - get: postgis_gppkg_source
+          resource: postgis215_gppkg_gpdb5_centos6
+        - get: postgis_gppkg_target
+          resource: postgis215_gppkg_gpdb6_centos6
+    - put: terraform
+      params:
+        <<: *ccp_default_params
+        vars:
+          standby_master: true
+          instance_type: n1-standard-2
+          number_of_nodes: 4
+          PLATFORM: centos6
+          # Decrease the reap time from the default of 8 hours now that there are
+          # both centos6 and centos7 jobs in order to not overload concourse.
+          ccp_reap_minutes: 180
+    - task: gen_source_cluster
+      file: ccp_src/ci/tasks/gen_cluster.yml
+      params:
+        <<: *ccp_gen_cluster_default_params
+        PLATFORM: centos6
+        GPDB_RPM: true
+      input_mapping:
+        gpdb_rpm: rpm_gpdb_source
+    - task: gpinitsystem_source_cluster
+      file: ccp_src/ci/tasks/gpinitsystem.yml
+    - task: prepare_installation
+      config:
+        platform: linux
+        image_resource:
+          type: registry-image
+          source:
+            repository: alpine
+            tag: latest
+        inputs:
+          - name: gpupgrade_src
+          - name: cluster_env_files
+          - name: rpm_enterprise
+          - name: rpm_gpdb_target
+        run:
+          path: gpupgrade_src/ci/scripts/prepare-installation.sh
+          args:
+            - greenplum-db-5
+            - greenplum-db-6
+    - task: load_extensions
+      config:
+        platform: linux
+        image_resource:
+          type: registry-image
+          source:
+            repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
+            tag: latest
+        inputs:
+          - name: ccp_src
+          - name: cluster_env_files
+          - name: gpupgrade_src
+          - name: postgis_gppkg_source
+          - name: sqldump
+        run:
+          path: gpupgrade_src/ci/scripts/load-extensions.bash
+    - task: upgrade_extensions
+      config:
+        platform: linux
+        image_resource:
+          type: registry-image
+          source:
+            repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
+            tag: latest
+        inputs:
+          - name: ccp_src
+          - name: cluster_env_files
+          - name: gpupgrade_src
+          - name: postgis_gppkg_target
+        run:
+          path: gpupgrade_src/ci/scripts/upgrade-extensions.bash
+      params:
+        USE_LINK_MODE: 1
+        FILTER_DIFF: 1
+        DIFF_FILE: postgis.diff
+    - task: validate_mirrors_and_standby
+      config:
+        platform: linux
+        image_resource:
+          type: registry-image
+          source:
+            repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
+            tag: latest
+        inputs:
+          - name: gpupgrade_src
+          - name: ccp_src
+          - name: cluster_env_files
+        run:
+          path: bash
+          args:
+            - -c
+            - |
+              set -eux -o pipefail
+
+              ./ccp_src/scripts/setup_ssh_to_cluster.sh
+
+              # Load the finalize test library.
+              source gpupgrade_src/test/acceptance/helpers/finalize_checks.bash
+
+              echo 'Doing failover tests of mirrors and standby...'
+              validate_mirrors_and_standby /usr/local/greenplum-db-target mdw 5432
+  ensure:
+    <<: *set_failed
+  on_success:
+    <<: *ccp_destroy
+  on_failure:
+    <<: *slack_alert
+
 - name: 5-to-6-link-mode-centos-7
   serial_groups: [5-to-6-link-mode]
   # Specifying serial groups so that only one platform runs at a time. For
@@ -2317,6 +2511,143 @@ jobs:
     <<: *ccp_destroy
   on_failure:
     <<: *slack_alert
+
+- name: 5-to-6-extensions-centos-7
+  serial_groups: [5-to-6-extensions]
+  # Specifying serial groups so that only one platform runs at a time. For
+  # example, 5-to-6-centos7 will only run after 5-to-6-centos6 completes. This
+  # will prevent concourse from becoming overloaded.
+  plan:
+    - in_parallel:
+        - get: rpm_enterprise
+          trigger: true
+          passed: [ build ]
+        - get: gpupgrade_src
+          passed: [ build ]
+        - get: rpm_gpdb_source
+          resource: rpm_gpdb5_centos7
+          trigger: true
+        - get: rpm_gpdb_target
+          resource: rpm_gpdb6_centos7
+          trigger: true
+        - get: ccp_src
+        - get: terraform.d
+          params:
+            unpack: true
+        # FIXME: this is not guaranteed to be the same dump generated by the
+        # above binary...
+        - get: sqldump
+          resource: postgis215_dump
+        - get: postgis_gppkg_source
+          resource: postgis215_gppkg_gpdb5_centos7
+        - get: postgis_gppkg_target
+          resource: postgis215_gppkg_gpdb6_centos7
+    - put: terraform
+      params:
+        <<: *ccp_default_params
+        vars:
+          standby_master: true
+          instance_type: n1-standard-2
+          number_of_nodes: 4
+          PLATFORM: centos7
+          # Decrease the reap time from the default of 8 hours now that there are
+          # both centos6 and centos7 jobs in order to not overload concourse.
+          ccp_reap_minutes: 180
+    - task: gen_source_cluster
+      file: ccp_src/ci/tasks/gen_cluster.yml
+      params:
+        <<: *ccp_gen_cluster_default_params
+        PLATFORM: centos7
+        GPDB_RPM: true
+      input_mapping:
+        gpdb_rpm: rpm_gpdb_source
+    - task: gpinitsystem_source_cluster
+      file: ccp_src/ci/tasks/gpinitsystem.yml
+    - task: prepare_installation
+      config:
+        platform: linux
+        image_resource:
+          type: registry-image
+          source:
+            repository: alpine
+            tag: latest
+        inputs:
+          - name: gpupgrade_src
+          - name: cluster_env_files
+          - name: rpm_enterprise
+          - name: rpm_gpdb_target
+        run:
+          path: gpupgrade_src/ci/scripts/prepare-installation.sh
+          args:
+            - greenplum-db-5
+            - greenplum-db-6
+    - task: load_extensions
+      config:
+        platform: linux
+        image_resource:
+          type: registry-image
+          source:
+            repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
+            tag: latest
+        inputs:
+          - name: ccp_src
+          - name: cluster_env_files
+          - name: gpupgrade_src
+          - name: postgis_gppkg_source
+          - name: sqldump
+        run:
+          path: gpupgrade_src/ci/scripts/load-extensions.bash
+    - task: upgrade_extensions
+      config:
+        platform: linux
+        image_resource:
+          type: registry-image
+          source:
+            repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
+            tag: latest
+        inputs:
+          - name: ccp_src
+          - name: cluster_env_files
+          - name: gpupgrade_src
+          - name: postgis_gppkg_target
+        run:
+          path: gpupgrade_src/ci/scripts/upgrade-extensions.bash
+      params:
+        USE_LINK_MODE: 1
+        FILTER_DIFF: 1
+        DIFF_FILE: postgis.diff
+    - task: validate_mirrors_and_standby
+      config:
+        platform: linux
+        image_resource:
+          type: registry-image
+          source:
+            repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
+            tag: latest
+        inputs:
+          - name: gpupgrade_src
+          - name: ccp_src
+          - name: cluster_env_files
+        run:
+          path: bash
+          args:
+            - -c
+            - |
+              set -eux -o pipefail
+
+              ./ccp_src/scripts/setup_ssh_to_cluster.sh
+
+              # Load the finalize test library.
+              source gpupgrade_src/test/acceptance/helpers/finalize_checks.bash
+
+              echo 'Doing failover tests of mirrors and standby...'
+              validate_mirrors_and_standby /usr/local/greenplum-db-target mdw 5432
+  ensure:
+    <<: *set_failed
+  on_success:
+    <<: *ccp_destroy
+  on_failure:
+    <<: *slack_alert
 - name: publish-release-candidate
   plan:
     - in_parallel:
@@ -2337,10 +2668,12 @@ jobs:
             - 5-to-6-primaries-only-centos-6
             - 5-to-6-no-standby-centos-6
             - 5-to-6-retail-demo-centos-6
+            - 5-to-6-extensions-centos-6
             - 5-to-6-link-mode-centos-7
             - 5-to-6-primaries-only-centos-7
             - 5-to-6-no-standby-centos-7
             - 5-to-6-retail-demo-centos-7
+            - 5-to-6-extensions-centos-7
             - 6-to-6-multihost-gpupgrade-centos-6
             - 6-to-6-multihost-gpupgrade-centos-7
             - 5-to-6-multihost-gpupgrade-centos-6
@@ -2356,10 +2689,12 @@ jobs:
             - 5-to-6-primaries-only-centos-6
             - 5-to-6-no-standby-centos-6
             - 5-to-6-retail-demo-centos-6
+            - 5-to-6-extensions-centos-6
             - 5-to-6-link-mode-centos-7
             - 5-to-6-primaries-only-centos-7
             - 5-to-6-no-standby-centos-7
             - 5-to-6-retail-demo-centos-7
+            - 5-to-6-extensions-centos-7
             - 5-to-6-pg-upgrade-tests-centos-6
             - 5-to-6-pg-upgrade-tests-centos-7
             - 6-to-6-multihost-gpupgrade-centos-6
