ci: inline validate-mirrors-and-standby.bash
For trivial scripts its better to inline. This makes it easier to debug,
faster iteration by simply flying rather than needing to commit, less
files for indirection, etc.

diff --git a/ci/generated/pipeline.yml b/ci/generated/pipeline.yml
--- a/ci/generated/pipeline.yml
+++ b/ci/generated/pipeline.yml
@@ -655,12 +655,25 @@ jobs:
           type: registry-image
           source:
             repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
-            tag: "latest"
+            tag: latest
         inputs:
           - name: gpupgrade_src
+          - name: ccp_src
           - name: cluster_env_files
         run:
-          path: gpupgrade_src/ci/scripts/validate-mirrors-and-standby.bash
+          path: bash
+          args:
+            - -c
+            - |
+              set -eux
+
+              ./ccp_src/scripts/setup_ssh_to_cluster.sh
+
+              # Load the finalize test library.
+              source gpupgrade_src/test/acceptance/helpers/finalize_checks.bash
+
+              echo 'Doing failover tests of mirrors and standby...'
+              validate_mirrors_and_standby /usr/local/greenplum-db-target mdw 5432
   ensure:
     <<: *set_failed
   on_success:
@@ -765,12 +778,25 @@ jobs:
           type: registry-image
           source:
             repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
-            tag: "latest"
+            tag: latest
         inputs:
           - name: gpupgrade_src
+          - name: ccp_src
           - name: cluster_env_files
         run:
-          path: gpupgrade_src/ci/scripts/validate-mirrors-and-standby.bash
+          path: bash
+          args:
+            - -c
+            - |
+              set -eux
+
+              ./ccp_src/scripts/setup_ssh_to_cluster.sh
+
+              # Load the finalize test library.
+              source gpupgrade_src/test/acceptance/helpers/finalize_checks.bash
+
+              echo 'Doing failover tests of mirrors and standby...'
+              validate_mirrors_and_standby /usr/local/greenplum-db-target mdw 5432
   ensure:
     <<: *set_failed
   on_success:
@@ -880,12 +906,25 @@ jobs:
           type: registry-image
           source:
             repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
-            tag: "latest"
+            tag: latest
         inputs:
           - name: gpupgrade_src
+          - name: ccp_src
           - name: cluster_env_files
         run:
-          path: gpupgrade_src/ci/scripts/validate-mirrors-and-standby.bash
+          path: bash
+          args:
+            - -c
+            - |
+              set -eux
+
+              ./ccp_src/scripts/setup_ssh_to_cluster.sh
+
+              # Load the finalize test library.
+              source gpupgrade_src/test/acceptance/helpers/finalize_checks.bash
+
+              echo 'Doing failover tests of mirrors and standby...'
+              validate_mirrors_and_standby /usr/local/greenplum-db-target mdw 5432
   ensure:
     <<: *set_failed
   on_success:
@@ -995,12 +1034,25 @@ jobs:
           type: registry-image
           source:
             repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
-            tag: "latest"
+            tag: latest
         inputs:
           - name: gpupgrade_src
+          - name: ccp_src
           - name: cluster_env_files
         run:
-          path: gpupgrade_src/ci/scripts/validate-mirrors-and-standby.bash
+          path: bash
+          args:
+            - -c
+            - |
+              set -eux
+
+              ./ccp_src/scripts/setup_ssh_to_cluster.sh
+
+              # Load the finalize test library.
+              source gpupgrade_src/test/acceptance/helpers/finalize_checks.bash
+
+              echo 'Doing failover tests of mirrors and standby...'
+              validate_mirrors_and_standby /usr/local/greenplum-db-target mdw 5432
   ensure:
     <<: *set_failed
   on_success:
@@ -1111,12 +1163,25 @@ jobs:
           type: registry-image
           source:
             repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
-            tag: "latest"
+            tag: latest
         inputs:
           - name: gpupgrade_src
+          - name: ccp_src
           - name: cluster_env_files
         run:
-          path: gpupgrade_src/ci/scripts/validate-mirrors-and-standby.bash
+          path: bash
+          args:
+            - -c
+            - |
+              set -eux
+
+              ./ccp_src/scripts/setup_ssh_to_cluster.sh
+
+              # Load the finalize test library.
+              source gpupgrade_src/test/acceptance/helpers/finalize_checks.bash
+
+              echo 'Doing failover tests of mirrors and standby...'
+              validate_mirrors_and_standby /usr/local/greenplum-db-target mdw 5432
   ensure:
     <<: *set_failed
   on_success:
@@ -1428,12 +1493,25 @@ jobs:
           type: registry-image
           source:
             repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
-            tag: "latest"
+            tag: latest
         inputs:
           - name: gpupgrade_src
+          - name: ccp_src
           - name: cluster_env_files
         run:
-          path: gpupgrade_src/ci/scripts/validate-mirrors-and-standby.bash
+          path: bash
+          args:
+            - -c
+            - |
+              set -eux
+
+              ./ccp_src/scripts/setup_ssh_to_cluster.sh
+
+              # Load the finalize test library.
+              source gpupgrade_src/test/acceptance/helpers/finalize_checks.bash
+
+              echo 'Doing failover tests of mirrors and standby...'
+              validate_mirrors_and_standby /usr/local/greenplum-db-target mdw 5432
   ensure:
     <<: *set_failed
   on_success:
@@ -1544,12 +1622,25 @@ jobs:
           type: registry-image
           source:
             repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
-            tag: "latest"
+            tag: latest
         inputs:
           - name: gpupgrade_src
+          - name: ccp_src
           - name: cluster_env_files
         run:
-          path: gpupgrade_src/ci/scripts/validate-mirrors-and-standby.bash
+          path: bash
+          args:
+            - -c
+            - |
+              set -eux
+
+              ./ccp_src/scripts/setup_ssh_to_cluster.sh
+
+              # Load the finalize test library.
+              source gpupgrade_src/test/acceptance/helpers/finalize_checks.bash
+
+              echo 'Doing failover tests of mirrors and standby...'
+              validate_mirrors_and_standby /usr/local/greenplum-db-target mdw 5432
   ensure:
     <<: *set_failed
   on_success:
@@ -1861,12 +1952,25 @@ jobs:
           type: registry-image
           source:
             repository: gcr.io/data-gpdb-public-images/gpdb6-centos7-test-golang
-            tag: "latest"
+            tag: latest
         inputs:
           - name: gpupgrade_src
+          - name: ccp_src
           - name: cluster_env_files
         run:
-          path: gpupgrade_src/ci/scripts/validate-mirrors-and-standby.bash
+          path: bash
+          args:
+            - -c
+            - |
+              set -eux
+
+              ./ccp_src/scripts/setup_ssh_to_cluster.sh
+
+              # Load the finalize test library.
+              source gpupgrade_src/test/acceptance/helpers/finalize_checks.bash
+
+              echo 'Doing failover tests of mirrors and standby...'
+              validate_mirrors_and_standby /usr/local/greenplum-db-target mdw 5432
   ensure:
     <<: *set_failed
   on_success:
